start.sh

Since we're now running with 1 worker per container in prod, let's update this default.

Updates WORKER_PROCESSES default value

---

itest/test/spectre/zipkin_test.py
lua/zipkin.lua

We've updated syslog2scribe to support firehose mode, so we now need to always send the zipkin span to it.

Always emit zipkin spans to syslog

---

itest/data/srv-configs/backend.main.yaml
itest/test/spectre/spectre_test.py
lua/caching_handlers.lua
lua/spectre_common.lua
tests/lua/caching_handlers_test.lua

When id extraction (for invalidation) is enabled for normal endpoints, we need to do it both when reading and writing. Otherwise `get_bucket` returns inconsistent values and we end up with 100% cache misses even if you keep asking for the same url. Fixes #14 
Added new itest to cover this issue. Was failing with the old code, passing now.

fix caching with id extraction enabled

---

itest/test/spectre/internal_spectre_test.py
lua/config_loader.lua
lua/internal_handlers.lua

`casper.internal` is a reserved namespace and doesn't need to be in services.yaml

Ignore the fact casper.internal is not in services.yaml

---

Dockerfile.opensource

This resolves #21. Since we have our own internal Dockerfile I'll mirror this internally once this PR gets approved.

Rewrite SIGTERM to SIGQUIT to let nginx shutdown gracefully

---

Makefile
itest/cassandra/Dockerfile
itest/cassandra/spectre_db.cache_store.cql
itest/test/spectre/internal_spectre_test.py

This greatly simplifies our task in acceptance tests since the cassandra docker image will be already ready and we won't have to create the schema manually.
I also removed the id_set column and index that we no longer use.

Bake cassandra schema in docker image

---

lua/spectre_common.lua

Our metrics have been weird since we dropped the hostname dimension. It looks like statsd isn't able to properly count the number of timers we send.
On the other hand, `spectre.bulk_hit_rate` (which is a counter) worked without problem. So I'm just gonna emit another counter for the normal hit rate instead of relying on the statsd aggregation.

Emit hit_rate metric

---

config/nginx.conf
itest/data/srv-configs/casper.internal.yaml
itest/docker-compose.yml
lua/datastores.lua
lua/http.lua
lua/metrics_helper.lua
lua/zipkin.lua
start.sh
tests/data/srv-configs/casper.internal.yaml
tests/lua/metrics_helper_test.lua
tests/lua/spectre_common_test.lua
tests/lua/zipkin_test.lua

Removes remaining env variables and uses the config file for all modules. The only env variables left are `SRV_CONFIGS_PATH`, `SERVICES_YAML_PATH`, `PAASTA_SERVICE` and `PAASTA_INSTANCE`.
We can't create sockets at import time anymore since at that point the config file hasn't been loaded yet, so I changed them to be singletons. It's cleaner anyway.

Use config file for everything

---

Dockerfile.opensource
config/nginx.conf
itest/test/spectre/spectre_test.py

There's a bit more description in #27 but in short we need to set both `underscores_in_headers on` and `lua_transform_underscores_in_response_headers off` to allow headers to contain underscores.
We also need a newer version of lua-resty-http since the old one was converting `_` to `-`

Allow underscores in header names

---

itest/data/srv-configs/casper.internal.yaml
itest/docker-compose.yml
itest/metrics/Dockerfile
itest/metrics/listen.py
itest/test/spectre/metrics_test.py
itest/test/spectre/spectre_test.py
itest/test/spectre/zipkin_test.py
itest/test/util.py
lua/main.lua
lua/metrics_helper.lua

Our refactorings keep messing up our metrics. This PR fixes them and adds a few itests to make sure we don't break them again in the future.
The itest coverage is poor (i.e. I don't test what happens in case of cache hits) but I don't have time right now to write more test cases. We can do that as a follow up PR.

Fix metrics and add a few metrics itests

---

config/nginx.conf
lua/main.lua
lua/traceback.lua
tests/lua/traceback_test.lua

This commit contains:
* a fix to ensure that full tracebacks are captured when Casper crashes in the middle of the request lifecycle
* an improvement to stop logging error-level messasges to both stdout and stderr
* a re-ordering of imports in `main.lua` (they're now alphabetized)
-------
Tested this both by adding a unit test and making Casper crash on purpose to look at the resulting log line:
```
2018/07/02 21:41:33 [error] 9#9: *2 [lua] spectre_common.lua:35: log(): {"critical":true,"err":"/code/lua/internal_handlers.lua:52: attempt to index local 'status_info' (a nil value)\n\n\tstack traceback:\n\t/code/lua/main.lua:49: in function '__newindex'\n\t/code/lua/internal_handlers.lua:52: in function 'fn'\n\t/code/lua/internal_handlers.lua:159: in function …
```

Log full tracebacks when critical errors happen

---

itest/test/spectre/conftest.py
itest/test/spectre/internal_spectre_test.py
lua/internal_handlers.lua

Having the healthcheck query cassandra was proven to be a bad idea. If
cassandra is overloaded, that'd cause the healthcheck to fail. That in
turns causes the client HAProxy to run out of healthy backends to route
requests to and return 503 errors.
It's still useful to be able to healthcheck cassandra for itests, since
we don't want to start running tests until Cassandra is ready. So I made
checking cassandra optional. We only check it if `check_cassandra=true`
is set in the HTTP request.

Make Cassandra healthcheck optional.

---

lua/datastores.lua
lua/http.lua
lua/metrics_helper.lua
lua/spectre_common.lua
lua/zipkin.lua
tests/lua/datastores_test.lua
tests/lua/metrics_helper_test.lua
tests/lua/spectre_common_test.lua

This PR adds a new `disable_caching` flag that can be used to disable caching for all namespaces and caches. This is sometimes useful to easily turn off caching in a specific region.

Add disable_caching flag to disable caching

---

config/nginx.conf
lua-cassandra-dev-0.rockspec

This branch/commit (https://github.com/kaisen/lua-cassandra/commit/470a5304ba54ae2be41da971acb518d494b4df37) contains logging that records how long responses are hanging when sending. This will help debug timing spikes.

Use kaisen's lua-cassandra to debug how often responses are hanging

---

itest/data/srv-configs/casper.internal.yaml
itest/test/spectre/spectre_test.py
itest/test/util.py
lua/main.lua
lua/spectre_common.lua
lua/zipkin.lua
tests/data/srv-configs/casper.internal.yaml
tests/lua/spectre_common_test.lua

This incorporates @bplotnick's work which I haven't touched yet. Maybe we need to not-hardcode the `spectre.main` value that is being injected? I see that HAProxy gets a hold of a `proxied_through` value to inject the same header but when we're in Casper we know it's gonna be `spectre.main`.
Test-wise, I've gotten around to figure out how Casper does tests and itests and it turns out we use a fake backend behind Casper to return whatever was sent to it, so I just make a request that doesn't have a `X-Smartstack-Source` header and check if the backend received one.

Inject X-Smartstack-Source header in Casper

---

config/nginx.conf
itest/test/spectre/spectre_test.py
itest/test/util.py
start.sh

Tests:
Setting the env variable to 1
```
Healthcheck succeeded!: 'http request succeeded, code 200' 
Your service is now running! Tailing stdout and stderr:
Disabling access log on stdout: done
```
```
dev1-uswest1cdevc:~/git/casper % curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:54423/status
200%
```
No logs are written to stdout
Not setting or setting the environment variable to something else that 1
```
container [130d941bdc9c]: Set env var DISABLE_STDOUT_ACCESS_LOG to 1 to disable stdout access logging
```
logs are displayed as usual
Changing the access logging in nginx.conf
container [19a54d04852d]: Disabling access log on stdout: error disabling stdout access_logs
Container exited with code 1

Adding option to disable stdout logs

---

itest/docker-compose.yml
start.sh

There was a problem in my previous sed syntax. I was fortunately able to catch the issue with the following error log:
`Disabling access log on stdout: error disabling stdout access_logs`
This is a better way of making sure that we exit with code 3 if no substitution has been made.
```
~/git/casper/config % cp nginx.conf test && sed -i -e "/access_log \/dev\/stdout main_spectre;/,\${s//access_log off;/;b};\$q3" test ;echo $? ; diff nginx.conf test                             (git)-[master]
0
21c21
<     access_log /dev/stdout main_spectre;
---
>     access_log off;
~/git/casper/config % cp nginx.conf test && sed -i -e "/access_log \/dev\/stdout main_GHOST;/,\${s//access_log off;/;b};\$q3" test ;echo $? ; diff nginx.conf test                               (git)-[master]
3
```

Fix bogus sed expression

---

Dockerfile.opensource
itest/docker-compose.yml

Jenkins changes the DOCKER_TAG variable, which makes cook-image create
an image with a different name.
Right now docker-compose expects the image to be called
spectre-dev-$USER, which isn't true anymore. The easiest way to fix this
is to rebuild the image during itests. All the layers should be cached
so it's gonna be very fast.
NOTE: this means that even internally in jenkins itests will always use the
opensource image and not the yelp specific one.

Build image again in itests

---

.dockerignore
.gitignore
.luacov
.travis.yml
Dockerfile.opensource
Makefile
README.md
casper-dev-0.rockspec
config/nginx.conf
luawrapper
opm-dependencies.txt
start.sh
tests/data/srv-configs/casper.internal.yaml
tests/lua/config_loader_test.lua
tests/lua/datastores_test.lua
tests/lua/metrics_helper_test.lua
tests/lua/spectre_common_test.lua
tests/lua/zipkin_test.lua

With this change unit tests will run locally and not inside docker. This also allows you to run casper locally which greatly increases debugging speed since you don't have to deal with docker.
luarocks dependencies are now installed under luarocks/ and no longer system wide, so that we don't mess up the devbox or laptop.
The luawrapper script and luarocks make target have been mostly copied from the routing service. However I'm using the system luarocks instead of building it myself since crc32 won't install with a manually built luarocks since it has some weird build incompatibility with luajit.
```
drolando@dev128-uswest1adevc casper (git run_tests_locally) ✓
~>  make test
rm -f luacov.stats.out luacov.report.out
Running tests for tests/lua/caching_handlers_test.lua …
```

Run tests and casper locally and not in a docker container

---

itest/casper/Dockerfile
itest/docker-compose.yml
itest/test/Dockerfile
itest/test/spectre/conftest.py
lua-cassandra-dev-0.rockspec
lua/datastores.lua
tests/lua/datastores_test.lua

The main change here is upgrading to `lua-cassandra==1.5.0`.
There was some change in what arguments the library expects as it doesn't like it anymore if we pass the seeds nodes as `ip:port` and instead only wants ips.  Passing also the port causes something in the code to get confused and the first node (the one used to discover the cluster) ends up with its `data_center` property being `nil`.
Also the new version doesn't like that we initialize the cluster object before cassandra is up, so I've added the `wait-for-it.sh` script that will wait up to 90 seconds until something starts listening on the target ip:port
FYI @thibaultcha

use newer lua cassandra

---

itest/test/spectre/spectre_test.py
itest/test/util.py

Fix itests by using `assert_is_in_spectre_cache` to verify cache hits. It already supports the post endpoints, not sure why we didn't use it the first time

Fix itests

---

config/nginx.conf
itest/test/spectre/internal_spectre_test.py

This will let us emit metrics on how many connections each instance in
handling and whether it's overloaded (e.g. connections in waiting
status).

Expose nginx-status endpoint

---

lua/spectre_common.lua
tests/lua/spectre_common_test.lua

When using envoy to route outgoing requests, we need to add the correct
Host header. However if we mutate the request headers this will cause
the cache keys to change as well, since 'Host' could be part of the
cache key if it's listed as Vary header.
Let's instead make a copy and mutate that instead.

Don't mutate the request headers

---

lua/spectre_common.lua
tests/lua/spectre_common_test.lua

The clone_table function I copied from the official docs doesn't work. The new table is empty.
This simple for loop is enough to create a shallow copy and this time I've also added better tests to make sure it's working

Fix clone_table function

---

lua/spectre_common.lua
tests/lua/spectre_common_test.lua

When we check whether the pragma no-cache header or the context-type
headers are set we need to remember that header keys are case
insensitive and that they're also - vs _ insensitive.
For some reason envoy lowercases all response headers, breaking this
logic if we don't handle them properly.

Header keys are case insensitive

---

lua/spectre_common.lua
tests/lua/spectre_common_test.lua

Since this is the only difference between haproxy and envoy I'm quite
sure that this is what's causing the weird errors in prod.
Turns out that Host is not a vary-header for any service and so it's
never part of any cache key, so it should be fine to mutate the request
headers.

Stop cloning the request headers

---

config/nginx.conf

i think this will make all errors go to stderr (and therefore paasta_app_output) and not how it is now, where some go to `/code/logs/error.log`. i think this is all that's needed in the casper repo
make test  and make itest are both green

Move the error destination config line from section http to main

---

lua/bulk_endpoints.lua
lua/caching_handlers.lua
lua/spectre_common.lua
tests/lua/caching_handlers_test.lua
tests/lua/spectre_common_test.lua

Adding an X-Original-Status response header to improve debugging. We can later pull this data into our logs etc. This captures the status code from all downstream requests, errors or otherwise.
There is some overlap with the `CACHE_STATUS` header, although this particular header is not always present depending on the request, so there still appears to be value in having a dedicated downstream status code header.
Added for bulk endpoints also, although the code coverage in that area is very limited.
Also set the X-Original-Status header to -1 if we didn't actually get a response from the origin (but inferred the response status).
Code is passing tests (I added an extra test too):
```
Total: 0 warnings / 0 errors in 14 files
./luawrapper luacov …
```

Adding an original status header which records the downstream response status code

---

lua/spectre_common.lua
tests/lua/spectre_common_test.lua
tests/lua/util_test.lua

The error log message will look similar to the following (note I temporarily adjusted the code to log a 4xx message for the output below):
```
2021/09/14 05:42:28 [error] 22449#22449: *2 [lua] spectre_common.lua:36: log():
{"critical":false,"err":"X-Original-Status: 404, message: <error message here>"},
client: 127.0.0.1, server: , request: "GET /category_yel HTTP/1.1", host: "internalapi"
```
I did intend to update the unit tests to check that the log function was being called, but I ran into some suspected scoping issues when using the busted `spy` methods. That being said, test coverage is running over the new lines of code:
```
-- Log any "no_response" errors
1         local log_error_message = HEADERS.ORIGINAL_STATUS .. ": -1, message: " .. error_message
1         log(ngx.ERR, { …
```

Error logging for 5xx and -1 downstream responses, unit test improvements

---

lua-cassandra-dev-0.rockspec

Updating Casper to use the https://github.com/Yelp/lua-cassandra fork, rather than drolandos.
Said fork also uses version 1.5.1 of the upstream rather than 1.5.
The upstream changes don't seem concerning, covered here:
https://github.com/thibaultcha/lua-cassandra/blob/master/CHANGELOG.md
So far this is passing the tests:
**Unit**
```
Checking lua/bulk_endpoints.lua                   OK
Checking lua/caching_handlers.lua                 OK
Checking lua/config_loader.lua                    OK
Checking lua/datastores.lua                       OK
Checking lua/entry_point.lua                      OK
Checking lua/http.lua                             OK
Checking lua/internal_handlers.lua                OK
Checking lua/itest_post_request_handlers.lua      OK
Checking lua/main.lua …
```

Using updated lua-cassandra fork

---

Cargo.lock
Makefile
itest/create_table.json
itest/data/srv-configs/casper.internal.yaml
itest/docker-compose.yml
itest/test/spectre/metrics_test.py
itest/test/spectre/spectre_test.py
itest/test/util.py
lua/spectre_common.lua
plugin/src/lib.rs
runtime/Cargo.toml
runtime/casper.toml
runtime/src/backends/dynamodb.rs
runtime/src/backends/mod.rs

**This code is a proof of concept, there are many production ready improvements that are required.**
**This PR includes:**
- The backend DynamoDB code utilising Rusoto
- Adjustments to the plugin code to use this backend, instead of using the memory backend
- Integration test additions to include a localstack instance, create the initial casper table etc, which is required to run the tests
- The addition of sleeps to the Python Integration tests, ultimately to avoid race conditions which cause the tests to fail, but won't be problems in the real world. Longer term we need a better more deterministic way of solving this.
- A mechanism to configure the percentage of traffic which is directed to the DynamoDB backend vs the Cassandra backend
- Connector setup logic to support both AWS and …

Added DynamoDB backend support with a configurable amount of traffic, performance metric updates and associated test changes

---

Makefile
itest/docker-compose.yml
plugin/src/lib.rs

This has been tested locally with the 2nd Redis backend removed (ensuring that the 2nd backend is indeed only optional)

Add support for an optional 2nd Redis backend

---

itest/test/spectre/metrics_test.py
lua/metrics_helper.lua
tests/lua/metrics_helper_test.lua

Adds `cache_status` (hit or miss) to the request timing metrics dimensions, allowing us to differentiate between the request timings for both cached and non cached (forwarded to downstream) requests.

Add cache_status to emit_request_timing

---

casper-server/src/lua/fs.rs

Required for the internal `/status` endpoint populating a list of configured services. This function is then made accessible to the Lua code.
In Lua, this is called as follows:
```
local core = require("core")
local files = core.fs.get_files_in_dir(PATH)
```

Add get_files_in_dir function

---

lua/v2_helper.lua

We've been getting timed out while making connections, increasing the TTL to 4s to see if this helps in reducing the dropped connections.

Increasing the purge timeout to 4s instead of 1s 

---

casper-server/src/lua/core.rs
casper-server/src/lua/log.rs
casper-server/src/lua/mod.rs

In the Lua environment this is called as follows:
```
local core = require("core")
local log = core.log
log.info("Log message")
```
Example log output:
```
2022-08-10T12:54:51.205240Z  INFO handler{method=GET uri=/status}: casper_server::lua::log: Success - loading config: {"casper_config":"present" ...}
```

Add lua log module and functions

---

casper-server/src/lua/utils.rs

A simple hash function, e.g. used to hash a requests fields to generate an id. Not intended as collision safe.

Add a simple lua hash function

---

casper-server/src/config.rs
casper-server/src/context.rs
casper-server/src/lua/tasks.rs
casper-server/src/metrics.rs

Added an optional configuration setting for a maximum number of in-flight background tasks.
If the configuration option is not set this defaults to `None` / no task limit.

Add a max background task limit
